application: transamerica-212623
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi.*
  script: api.api
  secure: always


libraries:
- name: endpoints
  version: latest